name: Normalize JSON File URLs

on:
  push:
    branches:
      - main  # Runs on push to the main branch, adjust if using a different branch
  pull_request:
    branches:
      - main  # Runs on PRs targeting the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  normalize_urls:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js to run a script (if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Install dependencies if needed (optional)
      - name: Install dependencies
        run: |
          npm install # Install any dependencies if you have a package.json

      # Step 4: Run your custom normalization script
      - name: Normalize URLs in JSON
        run: |
          node scripts/normalizeUrls.js

      # Optional Step 5: Commit and push changes back to the repository (if modifications are needed)
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Normalize URLs in JSON files"
          git push
