name: Normalize URLs

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (or choose a different branch)
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  normalize-urls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # You can specify your desired Node.js version here

    - name: Run normalize URLs script
      run: |
        node .github/scripts/normalize-urls.js  # Run the Node.js script that normalizes URLs
